### ISSUE TITLE
can't add useriq with yarn

### ISSUE THREAD

**Issue by awatt-cox** [useriq-com/useriq-react-native#12]
In an existing react-native project that uses yarn for dependency management, I tried to addd useriq-react-native according to your readme:
yarn add @useriq/useriq-react-native

I receive the error:
error Can't add "react-navigation": invalid package version undefined.

When I run the command in verbose mode, I can see that the failure happens when useriq is trying to install this dependency from the @useriq/useriq-react-native/package.json:
    "react-navigation": "git+https://github.com/react-navigation/react-navigation.git"

Why is this a dependency for useriq?

Please note that npm install @useriq/useriq-react-native succeeds, but the the app crashes when I run it.

Please fix this broken dependency so that it will install correctly. Thank you.

**Comment by awatt-cox** [comment]
Additional info: We are trying to add userIQ to a project that uses React-navigation **version 5**. I don't know if that's part of the issue.

**Comment by sudhakar** [comment]
@awatt-cox Thanks for reporting. We don't activity track issues on this repo. 

We've got the ticket via Zendesk. Will revert back to you soon.

BTW, react-navigation used in this repo is for a demo app and is no-longer required. Will issue a minor release removing the dependency.

**Comment by sudhakar** [comment]
@awatt-cox We have removed the dependency on react-navigation & released sdk v2.6.4 to [npm](https://www.npmjs.com/package/@useriq/useriq-react-native).
