### ISSUE TITLE
iOS13 modalpresentation style creates inconsistent behavior

### ISSUE THREAD

**Issue by awatt-cox** [useriq-com/useriq-react-native#8]
on iOS13, modal viewcontrollers do not fill the screen. Additionally, they can be dismissed by swiping down on the presented VC. This causes inconsistent behavior on UserIQ:

Steps to reproduce: 
- install UserIQReactNative in a project and run opn iOS13.x device or simulator.
- click the help tab
- UserIQ modal will be presented.
- click the BACK button on the UserIQ screen
- result: screen is dismissed and the help tab reappears on the app screen
- now, click the help tab again.
- UserIQ modal will be presented again.
- This time, swipe down to dismiss the UserIQ VC
- result: HELP TAB DOES NOT REAPPEAR.

It appears that the library is not correctly handling the iOS13 swipe-to-dismiss action for the modal VC.

**Comment by aravindgs** [comment]
This issue is currently being tracked in [Zendesk #4392](https://useriq.zendesk.com/agent/tickets/4392). Changes are already in the development branch. Will update once release is done

**Comment by aravindgs** [comment]
Issue resolved in #9. Update your UseriqReactNative library to 2.6.2
